### ISSUE TITLE
env.seed() is not supported

### ISSUE THREAD

**Issue by sbhambr1** [samjia2000/HSP#3]
Hi, how are you using env.seed() when its not supported by gym anymore? Getting stuck here: https://github.com/samjia2000/HSP/blob/ea110ff2d8e1185668968676f7c38817316e67e0/hsp/scripts/train/train_overcooked_sp.py#L30
(ps - i dont see any wrapper too so far, any help will be really appreciated!)

**Comment by Jackory** [comment]
I encountered the same issue. I just reinstall gym==0.20.0, it works.
