### ISSUE TITLE
The framework of PBT?

### ISSUE THREAD

**Issue by Jackory** [samjia2000/HSP#5]
Thank you for your nice implementation. However, after reading the code in depth, I am very troubled about the specific details of the implementation of PBT. Could you please provide **a flow chart to inform flow direction of PBT data and model**? Very appreciate.

**Comment by samjia2000** [comment]
How about describing the parts you have trouble with?

**Comment by Jackory** [comment]
Very appreciate for your response. I'm confused with:
1. what is the `map_ea2p` for ?
2. what is `active_policies`  and `active_trainers`?
3. As for the the implementation of Trajdi, the `other_action_log_prob` only considers one policy, but not all policies in the population,   which it not consistent with the average action probability defination in original Trajdi paper. https://github.com/samjia2000/HSP/blob/ea110ff2d8e1185668968676f7c38817316e67e0/hsp/algorithms/population/traj.py#L84,

**Comment by Jackory** [comment]
I agree with you. But I what I suspect is that the implementation of TrajDi diversity loss does not match the original paper.

**Comment by samjia2000** [comment]
> Very appreciate for your response. I'm confused with:
> 
> 1. what is the `map_ea2p` for ?
> 2. what is `active_policies`  and `active_trainers`?
> 3. As for the the implementation of Trajdi, the `other_action_log_prob` only considers one policy, but not all policies in the population,   which it not consistent with the average action probability defination in original Trajdi paper. https://github.com/samjia2000/HSP/blob/ea110ff2d8e1185668968676f7c38817316e67e0/hsp/algorithms/population/traj.py#L84
>    ,

For Q3, `trainer_idx` is a random index, so this is the average action probability in expectation.

**Comment by Jackory** [comment]
I don't think that's a reliable implementation.

**Comment by samjia2000** [comment]
Sure there could be better implementation ways concerning TrajeDi. You could have your own better implementation as well. Our way of implementing TrajeDi takes in consideration of efficiency, as you may find implementing the original objective could be highly in-efficient when the pool size is large. Actually TrajeDi takes the longest training time among all baselines. Again, sure you could have your own better implementation.
