### ISSUE TITLE
Prioritized Sampling

### ISSUE THREAD

**Issue by xihuai18** [samjia2000/HSP#7]
There are two types:
1. `use_advantage_prioritized_sampling`
2. `mep_use_prioritized_sampling`

Which one should I use to reproduce the results of FCP, MEP and HSP, especially HSP?

**Comment by samjia2000** [comment]
We do not use prioritized sampling when training FCP, MEP, and HSP since we found prioritized sampling not helpful in our ablation study. Detailed training scripts have also been provided in this repo.
