### ISSUE TITLE
Hidden Reward

### ISSUE THREAD

**Issue by xihuai18** [samjia2000/HSP#8]
https://github.com/samjia2000/HSP/blob/ea110ff2d8e1185668968676f7c38817316e67e0/hsp/envs/overcooked/Overcooked_Env.py#L527-L530

https://github.com/samjia2000/HSP/blob/ea110ff2d8e1185668968676f7c38817316e67e0/hsp/envs/overcooked/Overcooked_Env.py#L544-L545

"Have you mistakenly inverted the reward twice based on the `agent_index`? Could there be an error?"

**Comment by samjia2000** [comment]
I double check here and we are not making mistakes actually. In Line 527-Line530, it swaps $w$, not the reward/shaped info. Line 544-Line 545 swaps the reward.

**Comment by xihuai18** [comment]
https://github.com/samjia2000/HSP/blob/ea110ff2d8e1185668968676f7c38817316e67e0/hsp/envs/overcooked/Overcooked_Env.py#L531-L532

https://github.com/samjia2000/HSP/blob/ea110ff2d8e1185668968676f7c38817316e67e0/hsp/envs/overcooked/Overcooked_Env.py#L601-L607

https://github.com/samjia2000/HSP/blob/ea110ff2d8e1185668968676f7c38817316e67e0/hsp/envs/overcooked/Overcooked_Env.py#L400-L408

Thanks for replying, and I have another question, the `reward_shaping_factor=1` since you set `reward_shaping_horizon=0` when training HSP. Does this mean that the hidden utility and the default reward shaping are both used?

**Comment by xihuai18** [comment]
But in the paper and intuitively, I think the default reward shaping should not be using with the hidden utility together?

**Comment by samjia2000** [comment]
Yes, we use both the default reward shaping and the hidden utility. This actually doesn't contradict the whole framework. Using shaped reward & hidden utility is equivalent to using hidden utility but with a shifted sampling space for the reward weights.
